import type { Metadata } from 'next'
import './globals.css'
import Nav from './(components)/Nav';
import AuthProvider from './(components)/AuthProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-gray-100'>
        <Nav />
        <AuthProvider>
           <div className='m-2'>{children}</div>
        </AuthProvider>
      </body>
    </html>
  )
}
